version: "3.3"

services:
  tinu-server:
    image: tinu24/tinu-server
    container_name: tinu-server
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/rules.yml:/etc/prometheus/rules.yml
      - prom_data:/prometheus
    restart: unless-stopped

  nginx :
    image : nginx
    ports :
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - tinu-server

volumes:
  prom_data:
