name: '❌Delete'
description: 'Delete 작업 시 입력해주세요.'
labels: [🔥 Delete]
title: '❌[Delete] : '
body:
  - type: input
    id: description
    attributes:
      label: '무엇을 삭제하실 건가요?'
      description: '삭제할 기능에 대해서 간략히 설명해주세요.'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: '할 일은 무엇인가요?'
      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요.'
      value: |
        - [ ] 
    validations:
      required: true

  - type: checkboxes
    id: without_create_branch
    attributes:
      label: '브랜치 생성을 생략할까요?'
      description: '체크하면 브랜치가 자동으로 생성되지 않아요.'
      options:
        - label: 브랜치를 생성하지 않을래요.